mongo:
  enabled: false
  config:
    namespace: default
    connectionString: databases-mongodb.default.svc.cluster.local:27017
    storageAccount: backupsp3bd2
    container: backups
    path: /mongoBackup
    maxBackups: 3
    azureSecret: azure-storage-account-key
    secret: databases-mongodb
    name: mongo
    schedule: "0 */12 * * *"
    diskSize: 2
    storageClass: hostpath
    provider: Azure

mariadb:
  enabled: true
  config:
    socket: /opt/bitnami/mariadb/tmp/mysql.sock
    port: 3306
    host: databases-mariadb
    mariadbUser: root
    databaseName: my_database
    namespace: default
    connectionString: databases-mariadb.default.svc.cluster.local:3306
    storageAccount: backupsp3bd2
    container: backups
    path: /mariaBackup
    maxBackups: 3
    azureSecret: azure-storage-account-key
    secret: databases-mariadb
    name: mariadb
    schedule: "0 */12 * * *"
    diskSize: 2
    storageClass: hostpath
    provider: Azure

postgresql:
  enabled: false
  config:
    namespace: default

    connectionString: databases-postgresql.default.svc.cluster.local:5432
    storageAccount: backupsp3bd2
    container: backups
    path: /postgres
    maxBackups: 3
    azureSecret: azure-storage-account-key
    secret: databases-postgresql
    name: postgresql
    schedule: "0 */12 * * *"
    diskSize: 2
    storageClass: hostpath
    provider: Azure

neo4j:
  enabled: false
  config:
    namespace: default
    connectionString: databases-neo4j.default.svc.cluster.local
    storageAccount: backupsp3bd2
    container: backups
    path: /neo
    maxBackups: 3
    azureSecret: azure-storage-account-key
    secret: my-neo4j-auth
    name: neo4j
    schedule: "0 */12 * * *"
    diskSize: 2
    storageClass: hostpath
    provider: Azure
    username: neo4j


couchdb:
  enabled: false
  config:
    namespace: default
    connectionString: databases-couchdb.default.svc.cluster.local:5984
    storageAccount: backupsp3bd2
    container: backups
    path: /couch
    maxBackups: 3
    azureSecret: azure-storage-account-key
    secret: databases-couchdb
    name: couchdb
    schedule: "0 */12 * * *"
    diskSize: 2
    storageClass: hostpath
    provider: Azure

azure:
  storageAccount: backupsp3bd2
  container: backups
  azureSecret: azure-storage-account-key
  provider: Azure
